<?php

namespace App\PatientBundle\Entity;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{


    public function findPatients($filters = array())
    {
        $query =  $this->createQueryBuilder('U') ;
        foreach ($filters as $name=>$value) {
            switch ($name) {
                case "nom":
                    $query->andWhere("U.nom LIKE :$name")->setParameter($name,"%$value%") ;
                    break;
                case "prenom":
                    $query->andWhere("U.prenom LIKE :$name")->setParameter($name, "%$value%");
                    break;
                case "age":
                    $query->andWhere("U.age = :$name")->setParameter($name, "%$value%");
                    break;
                case "num_dossier":
                    $query->andWhere("U.num_dossier LIKE :$name")->setParameter($name, "%$value%");
                    break;
                default:
                    break;
            }
        }
        return $query->getQuery()->getResult();
    }
}
